library("methods")
library("R6")
library("Matrix")
library("Rcpp")
library("RcppEigen")
library("BH")
library("bitops")
library("MASS")
library("gmp")
library("R.utils")


source('~/GitHub/cvxr/R/globals.R')
source('~/GitHub/cvxr/R/generics.R')
source('~/GitHub/cvxr/R/utilities.R')
source('~/GitHub/cvxr/R/interface.R')
source('~/GitHub/cvxr/R/expressions.R')
source('~/GitHub/cvxr/R/constant.R')
source('~/GitHub/cvxr/R/variable.R')
source('~/GitHub/cvxr/R/lin_ops.R')
source('~/GitHub/cvxr/R/atoms.R')
source('~/GitHub/cvxr/R/affine.R')
source('~/GitHub/cvxr/R/problem.R')
source('~/GitHub/cvxr/R/constraints.R')
source('~/GitHub/cvxr/R/elementwise.R')
source('~/GitHub/cvxr/R/solver.R')
source('~/GitHub/cvxr/R/problem_data.R')
source('~/GitHub/cvxr/R/rcppUtils.R')
source('~/GitHub/cvxr/R/R6List.R')
source('~/GitHub/cvxr/R/ProblemData-R6.R')
source('~/GitHub/cvxr/R/LinOp-R6.R')
source('~/GitHub/cvxr/R/LinOpVector-R6.R')
source('~/GitHub/cvxr/R/RcppExports.R')
source('~/GitHub/cvxr/R/Solution-R6.R')
source('~/GitHub/cvxr/R/CVXcanon-R6.R')
source('~/GitHub/cvxr/R/Deque.R')
source('~/GitHub/cvxr/R/canonInterface.R')



