# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cpp_convolve <- function(xa, xb) {
    .Call('_CVXR_cpp_convolve', PACKAGE = 'CVXR', xa, xb)
}

.sweep_dgCmat_in_place <- function(A, c_part) {
    invisible(.Call('_CVXR_multiply_dgCMatrix_vector', PACKAGE = 'CVXR', A, c_part))
}

.sweep_in_place <- function(P, c_part) {
    invisible(.Call('_CVXR_sweep_in_place', PACKAGE = 'CVXR', P, c_part))
}

upper_tri_to_full <- function(n) {
    .Call('_CVXR_upper_tri_to_full', PACKAGE = 'CVXR', n)
}

