LinOp(type='neg',
      size=(1,
          1),
      args=[LinOp(type='neg',
                  size=(1,
                      1),
                  args=[LinOp(type='variable',
                              size=(1,
                                  1),
                              args=[],
                              data=0)],
                  data=None)],
      data=None)


LinLeqConstr(expr = LinOp(type = 'sum',
                          size=(1, 1),
                          args=[LinOp(type = 'mul',
                                      size =(1, 1),
                                      args = [LinOp(type = 'variable',
                                                  size = (2, 1),
                                                  args = [],
                                                  data = 1)],
                                      data = LinOp(type = 'dense_const',
                                                   size = (1, 2),
                                                   args = [],
                                                   data = matrix([[ 2.,  1.]]))),
                                LinOp(type = 'mul',
                                      size = (1, 1),
                                      args = [LinOp(type = 'variable',
                                                    size = (1, 1),
                                                    args = [],
                                                    data = 0)],
                                      data = LinOp(type = 'scalar_const',
                                                   size = (1, 1),
                                                   args = [],
                                                   data = 2.2360679774997898)),
                                LinOp(type = 'scalar_const',
                                      size = (1, 1),
                                      args = [],
                                      data = -1)],
                          data = None),
             constr_id = 2,
             size = (1, 1))


LinLeqConstr(expr=LinOp(type='sum',
                        size=(1, 1),
                        args=[LinOp(type='mul',
                                    size=(1, 1),
                                    args=[LinOp(type='variable',
                                                size=(2, 1),
                                                args=[],
                                                data=1)],
                                    data=LinOp(type='dense_const',
                                               size=(1, 2),
                                               args=[],
                                               data=matrix([[ 2., -1.]]))),
                              LinOp(type='mul',
                                    size=(1, 1),
                                    args=[LinOp(type='variable',
                                                size=(1, 1),
                                                args=[],
                                                data=0)],
                                    data=LinOp(type='scalar_const',
                                               size=(1, 1),
                                               args=[],
                                               data=2.2360679774997898)),
                              LinOp(type='scalar_const',
                                    size=(1, 1),
                                    args=[],
                                    data=-1)],
                        data=None),
             constr_id=3,
             size=(1, 1))


LinLeqConstr(expr=LinOp(type='sum',
                        size=(1, 1),
                        args=[LinOp(type='mul',
                                    size=(1, 1),
                                    args=[LinOp(type='variable',
                                                size=(2, 1),
                                                args=[],
                                                data=1)],
                                    data=LinOp(type='dense_const',
                                               size=(1, 2),
                                               args=[],
                                               data=matrix([[-1.,  2.]]))),
                              LinOp(type='mul',
                                    size=(1, 1),
                                    args=[LinOp(type='variable',
                                                size=(1, 1),
                                                args=[],
                                                data=0)],
                                    data=LinOp(type='scalar_const',
                                               size=(1, 1),
                                               args=[],
                                               data=2.2360679774997898)),
                              LinOp(type='scalar_const',
                                    size=(1, 1),
                                    args=[],
                                    data=-1)],
                        data=None),
             constr_id=4,
             size=(1, 1))

LinLeqConstr(expr=LinOp(type='sum', size=(1, 1), args=[LinOp(type='mul', size=(1, 1), args=[LinOp(type='variable', size=(2, 1), args=[], data=1)], data=LinOp(type='dense_const', size=(1, 2), args=[], data=matrix([[-1., -2.]]))), LinOp(type='mul', size=(1, 1), args=[LinOp(type='variable', size=(1, 1), args=[], data=0)], data=LinOp(type='scalar_const', size=(1, 1), args=[], data=2.2360679774997898)), LinOp(type='scalar_const', size=(1, 1), args=[], data=-1)], data=None), constr_id=5, size=(1, 1))
{}








LinOp(type=LEQ,
      size=[1, 1],
      args=[ LinOp(type=SUM,
                   size=[1, 1],
                   args=[ LinOp(type=MUL,
                                size=[1, 1],
                                args=[ LinOp(type=VARIABLE,
                                             size=[2, 1],
                                             args=[  ],
                                             data=[1]) ],
                                data=[2, 1]),
                         LinOp(type=MUL,
                               size=[1, 1],
                               args=[ LinOp(type=VARIABLE,
                                            size=[1, 1],
                                            args=[  ], data=[0]) ],
                               data=[2.23606797749979]),
                         LinOp(type=SCALAR_CONST,
                               size=[1, 1],
                               args=[  ],
                               data=[-1]) ],
                   data=[]) ],
      data=[2])



LinLeqConstr(expr=LinOp(type='sum',
                        size=(1, 1	),
                        args=[LinOp(type='mul',
                                    size=(1,
                                        1),
                                    args=[LinOp(type='variable',
                                                size=(2,
                                                    1),
                                                args=[],
                                                data=1)],
                                    data=LinOp(type='dense_const',
                                               size=(1,
                                                   2),
                                               args=[],
                                               data=matrix([[ 2.,
                                                             1.]]))),
                              LinOp(type='mul',
                                    size=(1,
                                        1),
                                    args=[LinOp(type='variable',
                                                size=(1,
                                                    1),
                                                args=[],
                                                data=0)],
                                    data=LinOp(type='scalar_const',
                                               size=(1,
                                                   1),
                                               args=[],
                                               data=2.2360679774997898)),
                              LinOp(type='scalar_const',
                                    size=(1,
                                        1),
                                    args=[],
                                    data=-1)],
                        data=None),
             constr_id=2,
             size=(1,
                 1))
LinLeqConstr(expr=LinOp(type='sum',
                        size=(1,
                            1),
                        args=[LinOp(type='mul',
                                    size=(1,
                                        1),
                                    args=[LinOp(type='variable',
                                                size=(2,
                                                    1),
                                                args=[],
                                                data=1)],
                                    data=LinOp(type='dense_const',
                                               size=(1,
                                                   2),
                                               args=[],
                                               data=matrix([[ 2.,
                                                             -1.]]))),
                              LinOp(type='mul',
                                    size=(1,
                                        1),
                                    args=[LinOp(type='variable',
                                                size=(1,
                                                    1),
                                                args=[],
                                                data=0)],
                                    data=LinOp(type='scalar_const',
                                               size=(1,
                                                   1),
                                               args=[],
                                               data=2.2360679774997898)),
                              LinOp(type='scalar_const',
                                    size=(1,
                                        1),
                                    args=[],
                                    data=-1)],
                        data=None),
             constr_id=3,
             size=(1,
                 1))
LinLeqConstr(expr=LinOp(type='sum',
                        size=(1,
                            1),
                        args=[LinOp(type='mul',
                                    size=(1,
                                        1),
                                    args=[LinOp(type='variable',
                                                size=(2,
                                                    1),
                                                args=[],
                                                data=1)],
                                    data=LinOp(type='dense_const',
                                               size=(1,
                                                   2),
                                               args=[],
                                               data=matrix([[-1.,
                                                             2.]]))),
                              LinOp(type='mul',
                                    size=(1,
                                        1),
                                    args=[LinOp(type='variable',
                                                size=(1,
                                                    1),
                                                args=[],
                                                data=0)],
                                    data=LinOp(type='scalar_const',
                                               size=(1,
                                                   1),
                                               args=[],
                                               data=2.2360679774997898)),
                              LinOp(type='scalar_const',
                                    size=(1,
                                        1),
                                    args=[],
                                    data=-1)],
                        data=None),
             constr_id=4,
             size=(1,
                 1))
LinLeqConstr(expr=LinOp(type='sum',
                        size=(1,
                            1),
                        args=[LinOp(type='mul',
                                    size=(1,
                                        1),
                                    args=[LinOp(type='variable',
                                                size=(2,
                                                    1),
                                                args=[],
                                                data=1)],
                                    data=LinOp(type='dense_const',
                                               size=(1,
                                                   2),
                                               args=[],
                                               data=matrix([[-1.,
                                                             -2.]]))),
                              LinOp(type='mul',
                                    size=(1,
                                        1),
                                    args=[LinOp(type='variable',
                                                size=(1,
                                                    1),
                                                args=[],
                                                data=0)],
                                    data=LinOp(type='scalar_const',
                                               size=(1,
                                                   1),
                                               args=[],
                                               data=2.2360679774997898)),
                              LinOp(type='scalar_const',
                                    size=(1,
                                        1),
                                    args=[],
                                    data=-1)],
                        data=None),
             constr_id=5,
             size=(1,
                 1))


