LinOp(id=76a356ef-7443-4938-87ee-0c46d9a2d97f,
      type=EQ,
      size=[4,
            1],
      args=[ LinOp(id=1b76975f-6143-4a75-b842-b779b1835064,
                   type=SUM,
                   size=[4,
                         1],
                   args=[ LinOp(id=02103d35-ea1a-47c8-a6a7-11d55889e325,
                                type=MUL,
                                size=[4,
                                      1],
                                args=[ LinOp(id=74cd4372-8521-41f7-b5ab-ebed3eaf0034,
                                             type=VARIABLE,
                                             size=[10,
                                                   1],
                                             args=[  ],
                                             sparse=FALSE,
                                             data=[4]) ],
                                sparse=FALSE,
                                data=[0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      1,
                                      0,
                                      0,
                                      0,
                                      0,
                                      1,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      1]),
                         LinOp(id=4a7d6f10-df00-4574-91e9-1e53bba43b31,
                               type=DENSE_CONST,
                               size=[4,
                                     1],
                               args=[  ],
                               sparse=FALSE,
                               data=[0,
                                     -1,
                                     -1,
                                     -1]) ],
                   sparse=FALSE,
                   data=[]) ],
      sparse=FALSE,
      data=[2]),
LinOp(id=4eac79a9-b592-426a-8381-1465b6d7f001,
      type=LEQ,
      size=[10,
            1],
      args=[ LinOp(id=87535211-6736-4f09-995c-052f111f8690,
                   type=SUM,
                   size=[10,
                         1],
                   args=[ LinOp(id=d13f05ed-d70a-45bf-94b9-5d97cfc9df7a,
                                type=PROMOTE,
                                size=[10,
                                      1],
                                args=[ LinOp(id=aa67dbd4-8db6-4e9a-80af-7108ef31f353,
                                             type=SCALAR_CONST,
                                             size=[1,
                                                   1],
                                             args=[  ],
                                             sparse=FALSE,
                                             data=[0]) ],
                                sparse=FALSE,
                                data=[]),
                         LinOp(id=5f7dd94e-f380-4dab-afd8-bb31671ad9c2,
                               type=NEG,
                               size=[10,
                                     1],
                               args=[ LinOp(id=5bc3fd1a-42d6-4e51-b5c0-9acceaa348bb,
                                            type=VARIABLE,
                                            size=[10,
                                                  1],
                                            args=[  ],
                                            sparse=FALSE,
                                            data=[4]) ],
                               sparse=FALSE,
                               data=[]) ],
                   sparse=FALSE,
                   data=[]) ],
      sparse=FALSE,
      data=[2]),
LinOp(id=9001c5d7-2bec-4b0b-ae8c-f5bfe06bdfd2,
      type=SOC,
      size=[3,
            1],
      args=[ LinOp(id=c46f93d5-cb0c-43b4-bae7-f2844b8ceb3c,
                   type=VARIABLE,
                   size=[1,
                         1],
                   args=[  ],
                   sparse=FALSE,
                   data=[11]),
            LinOp(id=61dbb43f-e12d-4085-a22a-26e53b87a541,
                  type=MUL,
                  size=[2,
                        1],
                  args=[ LinOp(id=d9f94c02-3c21-4505-921b-168b3ddaa59a,
                               type=VARIABLE,
                               size=[10,
                                     1],
                               args=[  ],
                               sparse=FALSE,
                               data=[4]) ],
                  sparse=FALSE,
                  data=[-1,
                        0,
                        1,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        -1,
                        0,
                        1,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0]) ],
      sparse=FALSE,
      data=[2]),
LinOp(id=8f81750e-3e4c-488b-bead-153df458e45d,
      type=LEQ,
      size=[1,
            1],
      args=[ LinOp(id=d4b22d65-a34a-42b4-9542-b071fb318cbd,
                   type=SUM,
                   size=[1,
                         1],
                   args=[ LinOp(id=4f78570d-12bd-4752-b88c-f02db2b50b27,
                                type=VARIABLE,
                                size=[1,
                                      1],
                                args=[  ],
                                sparse=FALSE,
                                data=[11]),
                         LinOp(id=2da84e0f-8353-4e9e-85e3-aed514a2f622,
                               type=SCALAR_CONST,
                               size=[1,
                                     1],
                               args=[  ],
                               sparse=FALSE,
                               data=[-0.5]) ],
                   sparse=FALSE,
                   data=[]) ],
      sparse=FALSE,
      data=[2]),
LinOp(id=c20930d2-ad16-44e2-9721-1d3a17a84e2c,
      type=SOC,
      size=[3,
            1],
      args=[ LinOp(id=689f4669-d75f-4713-b7a4-0cd26dd5963f,
                   type=VARIABLE,
                   size=[1,
                         1],
                   args=[  ],
                   sparse=FALSE,
                   data=[12]),
            LinOp(id=5ad381dc-d842-4708-8586-f209e4bba12d,
                  type=MUL,
                  size=[2,
                        1],
                  args=[ LinOp(id=b8c3a6ab-d6dd-4c36-b11a-8efdcc4c4cef,
                               type=VARIABLE,
                               size=[10,
                                     1],
                               args=[  ],
                               sparse=FALSE,
                               data=[4]) ],
                  sparse=FALSE,
                  data=[0,
                        0,
                        -1,
                        0,
                        1,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        -1,
                        0,
                        1,
                        0,
                        0,
                        0,
                        0]) ],
      sparse=FALSE,
      data=[2]),
LinOp(id=254fe986-e940-49ce-8d30-c6d5c20404f7,
      type=LEQ,
      size=[1,
            1],
      args=[ LinOp(id=ccb6527c-0585-4582-986a-60a72a637369,
                   type=SUM,
                   size=[1,
                         1],
                   args=[ LinOp(id=6c877b5c-93d4-4b46-9cf8-f7a06c5d5a0b,
                                type=VARIABLE,
                                size=[1,
                                      1],
                                args=[  ],
                                sparse=FALSE,
                                data=[12]),
                         LinOp(id=e325c948-bc34-4a0a-8bf0-c100509a0e2d,
                               type=SCALAR_CONST,
                               size=[1,
                                     1],
                               args=[  ],
                               sparse=FALSE,
                               data=[-0.5]) ],
                   sparse=FALSE,
                   data=[]) ],
      sparse=FALSE,
      data=[2]),
LinOp(id=3bbcab12-b2fc-4e7b-8f36-48b8f279ab30,
      type=SOC,
      size=[3,
            1],
      args=[ LinOp(id=7319b2ac-8698-4cdd-93f8-f4daa5b2b0c8,
                   type=VARIABLE,
                   size=[1,
                         1],
                   args=[  ],
                   sparse=FALSE,
                   data=[13]),
            LinOp(id=d54c52da-314c-4b3f-bcec-e1749527b410,
                  type=MUL,
                  size=[2,
                        1],
                  args=[ LinOp(id=6533b451-931e-49dd-85a6-07ab4b9a0605,
                               type=VARIABLE,
                               size=[10,
                                     1],
                               args=[  ],
                               sparse=FALSE,
                               data=[4]) ],
                  sparse=FALSE,
                  data=[0,
                        0,
                        0,
                        0,
                        -1,
                        0,
                        1,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        -1,
                        0,
                        1,
                        0,
                        0]) ],
      sparse=FALSE,
      data=[2]),
LinOp(id=52502d44-9906-41c0-8eca-bc0eb850a6d1,
      type=LEQ,
      size=[1,
            1],
      args=[ LinOp(id=641a3128-246d-498d-87ee-a61502e2084f,
                   type=SUM,
                   size=[1,
                         1],
                   args=[ LinOp(id=bfe17234-bffc-4cdf-8721-ca278ae93764,
                                type=VARIABLE,
                                size=[1,
                                      1],
                                args=[  ],
                                sparse=FALSE,
                                data=[13]),
                         LinOp(id=79e1cd55-62d2-4f29-bb34-ddcce156c908,
                               type=SCALAR_CONST,
                               size=[1,
                                     1],
                               args=[  ],
                               sparse=FALSE,
                               data=[-0.5]) ],
                   sparse=FALSE,
                   data=[]) ],
      sparse=FALSE,
      data=[2]),
LinOp(id=a60f1af6-e521-42b4-9550-756c19b62e1a,
      type=SOC,
      size=[3,
            1],
      args=[ LinOp(id=1500c78d-8962-4b00-a03d-8c8ec0ca482f,
                   type=VARIABLE,
                   size=[1,
                         1],
                   args=[  ],
                   sparse=FALSE,
                   data=[14]),
            LinOp(id=a434816c-4da4-49a5-a843-7de8ca6b5584,
                  type=MUL,
                  size=[2,
                        1],
                  args=[ LinOp(id=b8efeed4-3e33-43b1-9f66-6ebc31b3db3c,
                               type=VARIABLE,
                               size=[10,
                                     1],
                               args=[  ],
                               sparse=FALSE,
                               data=[4]) ],
                  sparse=FALSE,
                  data=[0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        -1,
                        0,
                        1,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        -1,
                        0,
                        1]) ],
      sparse=FALSE,
      data=[2]),
LinOp(id=d5b1a34d-2112-4390-8621-cb14cb3208a7,
      type=LEQ,
      size=[1,
            1],
      args=[ LinOp(id=a2a4f7c7-edb9-47c7-a673-bbb7c9c8db8a,
                   type=SUM,
                   size=[1,
                         1],
                   args=[ LinOp(id=457b2732-0241-4276-b680-b58e1b49198c,
                                type=VARIABLE,
                                size=[1,
                                      1],
                                args=[  ],
                                sparse=FALSE,
                                data=[14]),
                         LinOp(id=c0911497-2f62-4b28-a0ef-f040afde5214,
                               type=SCALAR_CONST,
                               size=[1,
                                     1],
                               args=[  ],
                               sparse=FALSE,
                               data=[-0.5]) ],
                   sparse=FALSE,
                   data=[]) ],
      sparse=FALSE,
      data=[2])
