#####
## DO NOT EDIT THIS FILE!! EDIT THE SOURCE INSTEAD: rsrc_tree/zzz_R_specific/set_old_class.R
#####

## The following allows us to use `S3` classes `data.frame` and `matrix` as slots in `S4` classes.
setOldClass("data.frame")
setOldClass("matrix")
