#####
## DO NOT EDIT THIS FILE!! EDIT THE SOURCE INSTEAD: rsrc_tree/lin_ops/canon_backend.R
#####

## CVXPY SOURCE: cvxpy/lin_ops/canon_backend.py

## We have only one canonical backend now, which is C++ based.
## BUT need to add Python and SCIPY backends using reticulate.
