#####
## DO NOT EDIT THIS FILE!! EDIT THE SOURCE INSTEAD: rsrc_tree/reductions/complex2real/canonicalizers/inequality_canon.R
#####

## CVXPY SOURCE: reductions/complex2real/canonicalizers/inequality_canon.py
## Inequality constraint canonicalizer

c2r_inequality_canon <- function(expr, real_args, imag_args, real2imag) {
  if (is.null(imag_args[[1L]]) && is.null(imag_args[[2L]])) {
    return(list(list(expr_copy(expr, real_args)), NULL))
  }

  ## Fill in missing imag args with zeros
  for (i in seq_along(imag_args)) {
    if (is.null(imag_args[[i]])) {
      imag_args[[i]] <- Constant(matrix(0, .shape(real_args[[i]])[1L],
                                        .shape(real_args[[i]])[2L]))
    }
  }

  imag_cons <- list(Inequality(imag_args[[1L]], imag_args[[2L]],
                               constr_id = real2imag[[as.character(.id(expr))]]))
  if (is.null(real_args[[1L]]) && is.null(real_args[[2L]])) {
    return(list(NULL, imag_cons))
  } else {
    ## Fill in missing real args with zeros
    for (i in seq_along(real_args)) {
      if (is.null(real_args[[i]])) {
        real_args[[i]] <- Constant(matrix(0, .shape(imag_args[[i]])[1L],
                                          .shape(imag_args[[i]])[2L]))
      }
    }
    return(list(list(expr_copy(expr, real_args)), imag_cons))
  }
}
