#####
## DO NOT EDIT THIS FILE!! EDIT THE SOURCE INSTEAD: rsrc_tree/reductions/dgp2dcp/canonicalizers/add_canon.R
#####

## CVXPY SOURCE: reductions/dgp2dcp/canonicalizers/add_canon.py
## DGP canonicalizer for AddExpression: log_sum_exp of log-space args

.dgp_add_canon <- function(expr, args) {
  ## Scalar case: log_sum_exp(hstack(args))
  if (expr_is_scalar(expr)) {
    return(list(log_sum_exp(do.call(hstack, args)), list()))
  }

  ## Promote scalar summands to expr shape
  summands <- lapply(args, function(s) {
    if (expr_is_scalar(s)) cvxr_promote(s, .shape(expr)) else s
  })

  rows <- list()
  if (length(.shape(expr)) == 1L || .shape(expr)[2L] == 1L) {
    ## Vector case: iterate over rows
    for (i in seq_len(.shape(expr)[1L])) {
      elems <- lapply(summands, function(s) s[i])
      row_elem <- log_sum_exp(do.call(hstack, elems))
      rows <- c(rows, list(list(row_elem)))
    }
  } else {
    ## Matrix case: iterate over rows and columns
    for (i in seq_len(.shape(expr)[1L])) {
      row <- list()
      for (j in seq_len(.shape(expr)[2L])) {
        elems <- lapply(summands, function(s) s[i, j])
        row <- c(row, list(log_sum_exp(do.call(hstack, elems))))
      }
      rows <- c(rows, list(row))
    }
  }
  result <- bmat(rows)
  if (!identical(.shape(result), .shape(expr))) {
    result <- reshape_expr(result, .shape(expr))
  }
  list(result, list())
}
