#####
## DO NOT EDIT THIS FILE!! EDIT THE SOURCE INSTEAD: rsrc_tree/reductions/dgp2dcp/canonicalizers/xexp_canon.R
#####

## CVXPY SOURCE: reductions/dgp2dcp/canonicalizers/xexp_canon.py
## DGP canonicalizer for Xexp: x*exp(x) → log(x) + x = x + exp(x)
## In log-space: log(x * exp(x)) = log(x) + x
## Args are already in log-space (so args[[1]] = log(x)).
## Result: args[[1]] + exp(args[[1]])  (matching CVXPY exactly)

.dgp_xexp_canon <- function(expr, args) {
  result <- args[[1L]] + exp(args[[1L]])
  list(result, list())
}
